---

- name: delete the 2 Loopback on equipement
  hosts: all
  connection: ansible.netcommon.network_cli
  tasks:
    - name: delete loopback shell
      with_items: "{{local_loopback}}"
      cisco.nxos.nxos_interface:
        name: "{{item.name}}"
        state: absent
