---

- name: Create 2 Loopback on equipement
  hosts: nexus9k
  connection: ansible.netcommon.network_cli
  tasks:
    - name: Created loopback shell
      with_items: "{{local_loopback}}"
      nxos_interface:
       name: "{{item.name}}"
       mode: layer3
       description: "{{item.desc}}"
       admin_state: up


    - name: Set the new loopback
      with_items: "{{local_loopback}}"
      nxos_l3_interface:
       state: present
       name: "{{item.name}}"
       ipv4: "{{item.ip_address}}/{{item.prefix}}"
